apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: biletado

commonLabels:
  app.kubernetes.io/part-of: biletado

resources:
  - https://gitlab.com/biletado/kustomize.git//overlays/kind

secretGenerator:
  - name: biletado-env-secret
    envs:
      - .env

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/felix26/biletado-backend:latest
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 9099
      
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEBUG_SERVER
          value: "False"

      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: biletado-env-secret
    target:
      group: apps
      version: v1
      kind: Deployment
      name: reservations